- src/objects/avcontrol.js
If play(0) is called in state 0 (‘stopped’), the A/V Control object SHALL automatically go to play state 2 (‘paused’).
> Fix AOD-70

- components/network_services/json_rpc/JsonRpcService.cpp
- components/network_services/json_rpc/JsonRpcService.h
Description:
- Change a connection data to BiasToSystemTime
- Use bias for seek-relative intents
- Change the data type of time offset to integer 
Testing:
- Sending intents of seek-content, seek-relative, seek-live and seek-wallcloc
> HTM-725 Fix bug: time offset and interval for state media

- src/objectmanager.js
Causes the following error when running org.hbbtv_00001407:
Unable to finalize test step 0 - the application failed to initialize with exception: TypeError: document.getElementById('appmgr').getOwnerApplication is not a function. (In 'document.getElementById('appmgr').getOwnerApplication(document)', 'document.getElementById('appmgr').getOwnerApplication' is undefined)
> Fix bug after code linter

- android/orblibrary/src/main/java/org/orbtv/orblibrary/IOrbSession.java
- android/orblibrary/src/main/java/org/orbtv/orblibrary/OrbSession.java
- android/orbpolyfill/src/main/java/org/orbtv/orbpolyfill/AbstractBridge.java
- src/mediaproxies/mediaelementextension.js
Description:
Some hbbtv tests require changing audio language(s) while the app is running explicitly by user interaction with the device. We only support selecting audio tracks either with HTMLmedia or A/V control using javascript APIs.
Proposed changes:
Provide support for changing audio language directly via orb session. Integration should call _dispatchPreferredAudioLanguageChanged_ so as bridge can propagate the language change to media manager. Will work for all supported formats/codecs.
Test:
org.hbbtv_EAC30013
> add support for changing preferred audio language by the user

- BuildPolyfill.mk
- android/mockorbapp/src/main/java/org/orbtv/mockorbapp/MockOrbSessionCallback.java
- android/orblibrary/src/main/cpp/application_manager_native.cpp
- android/orblibrary/src/main/java/org/orbtv/orblibrary/ApplicationManager.java
- android/orblibrary/src/main/java/org/orbtv/orblibrary/Bridge.java
- android/orblibrary/src/main/java/org/orbtv/orblibrary/IOrbSession.java
- android/orblibrary/src/main/java/org/orbtv/orblibrary/OrbSession.java
- android/orbpolyfill/src/main/java/org/orbtv/orbpolyfill/AbstractBridge.java
- android/orbpolyfill/src/main/java/org/orbtv/orbpolyfill/BridgeTypes.java
- components/application_manager/ait.cpp
- components/application_manager/ait.h
- components/application_manager/app.cpp
- components/application_manager/app.h
- components/application_manager/application_manager.cpp
- components/application_manager/application_manager.h
- rdk/ORB/library/src/core/SessionCallbackImpl.cpp
- rdk/ORB/library/src/core/SessionCallbackImpl.h
- src/bridge.js
- src/objects/applicationmanager.js
- src/objects/configuration/configuration.js
- src/objects/dashevent.js
- src/objects/programme.js
- src/objects/videobroadcast.js
* HTM-716: Support for StreamEvents with DVB-I.
* HTM-704: Force applications of type 1.2 and 2 to go up to CONNECTING state and never PRESENTING.
* HTM-704: Update the url parameters for applications of types 1.2 and 2.
* HTM-704: Add the ? character to the urlParams argument, otherwise the url parameters are not separated from the main body of the url.
* HTM-704: Slight refactoring with the application scheme to fix null object dereference on m_ait.Get() call.
* HTM-704: Fixed issue with faulty url params for the application scheme.
* HTM-716: Add support for DVB-I Stream Events.
* HTM-717: Consider parental rating schemes other than dvb-si when checking for blocked content.
* HTM-647: Return undefined if longDescription is not defined instead of falling back to the description.
* …
> Implementation of additional DVB-I features.

- src/mediaproxies/nativeproxy.js
Description:
WPE-WebKit returns strings of the following form "001", "002", ... as video and audio track ids. Apply a fix in nativeproxy to transform these strings to the following form: "1", "2", ...
Testing:
org.hbbtv_HTML50500
org.hbbtv_HTML50710
> org.hbbtv_HTML50500 (RDK)

- src/bridge.js
- src/utils.js
Description
There is an inconsistency between storing the dsd internally and passing the dsd to the native implementation. Provide a fix that will treat dsd as always being in base64 form when received from the platform. Decode it when requested and the channel is for idType ID_DVB_SI_DIRECT
Testing:
MITXperts get and set channel, channel list.
> HBBTV-34: Inconsistency between when a DSD is base64 encode/decode

- rdk/ORBBrowser/WebKitImplementation.cpp
Description:
Fix for regression caused by the introduction of hbbtv-carousel:// scheme on RDK
Tests:
org.hbbtv_DSMCC046
> Remove XHR caching for hbbtv-carousel scheme

- src/polyfill/xhr.js
Description:
Support 7.2.5.3 base tag for relative dvb urls
Tests:
BBC tc16
> Override xhr open in case of RDK native to create absolute dvb urls

- rdk/ORBBrowser/WebKitImplementation.cpp
Description:
WPE-2.38 requires an environment variable for the definition of protocols that need to be whitelisted in port checking. 
Whitelist dvb and hbbtv-carousel schemes
Tests:
org.hbbtv_DSMCC014
...
org.hbbtv_DSMCC019
org.hbbtv_DSMCC040
org.hbbtv_DSMCC044
org.hbbtv_DSMCC046
> Set env variable for port whitelisting (WPE-2.38)

- src/polyfill/xhr.js
Description:
Fix for overloading xhr open in case of rdk client
Tests:
org.hbbtv_AVC01040
org.hbbtv_AVC01050
org.hbbtv_AVC01060
> Use arguments object for xhr open overload

- src/objects/videobroadcast.js
Description
Also check if target url is an xse file in videobroadcast.js to pass org.hbbtv_DSMCC005, org.hbbtv_DSMCC007 and org.hbbtv_DSMCC008
Tests
org.hbbtv_DSMCC001
...
org.hbbtv_DSMCC143
> Fix regressions when targetURL is a .xse file

- components/network_services/media_synchroniser/media_synchroniser.cpp
Convert the extracted eventId in hex string format to integer and write the hex value to char buffer
> Fix wrong format when converting eventId from string to integer and writing the hex value to buffer

- src/mediaproxies/mediamanager.js
Add timeout to the XHR that requests HEAD info in order to upgrade the media element to the proper proxy.
> Add timeout to the XHR that requests HEAD info in order to upgrade the media element to the proper proxy.

- android/mock204app/src/main/java/org/orbtv/mock204app/MockOrbSessionCallback.java
- android/orblibrary/src/main/java/org/orbtv/orblibrary/IOrbSession.java
- android/orblibrary/src/main/java/org/orbtv/orblibrary/OrbSession.java
- components/application_manager/application_manager.cpp
- components/network_services/json_rpc/JsonRpcService.cpp
Description:
- Send a notification with the value of dialogueEnhancementGain field equal to value in dialogueEnhancementOverride request
- KEYCODE_ESCAPE is for supporting VK_EXIT
- When the dialogueEnhancementGain parameter value of "NOTAVALUE" a string, generate a valid JSON-RPC error response message with a code value of -24 and a message value of "Dialogue Enhancement override failed"
https://oceanbluesoftware.atlassian.net/jira/software/projects/HTM/boards/17/backlog?selectedIssue=HTM-785
https://oceanbluesoftware.atlassian.net/jira/software/projects/HTM/boards/17/backlog?selectedIssue=HTM-786
https://oceanbluesoftware.atlassian.net/jira/software/projects/HTM/boards/17/backlog?selectedIssue=HTM-782
> HTM-782, HTM-785 and HTM-786

- components/application_manager/application_manager.cpp
Description:
The BBC application performs the transition from BR to BI mode by incorrectly using the vbo.stop() method instead of vbo.setChannel(null). Whitelist the BBC IPlayer application from resetting the broadcast object, to treat it as a BI app.
Tests:
BBC IPlayer launch
> Do not reset the broadcast playback for the iPlayer (BBC) app

- src/polyfill/keyevent.js
Description:
BBC TC29 requires to iterate in the KeySet object. Set the enumerable property to true so that we can enable that.
Tests:
TC29
> Set enumerable on KeySet

- android/mock204app/src/main/java/org/orbtv/mock204app/MockOrbSessionCallback.java
Description:
- Addressed issue where dialogueEnhancementGain being 0 is now removed.
- Adjusted dialogue enhancement override process to ensure receiving one response message and a notification. The order has been updated, with the notification coming after the response.
Testing:
- Build image
- org.hbbtv_AC4-DE0120
- org.hbbtv_AC4-DE0110
- org.hbbtv_AC4-DE0160
- org.hbbtv_AC4-DE0003
- org.hbbtv_AC4-DE0080
- org.hbbtv_AC4-DE0070
> HTM-783 Dialogue Enhancement Update and Revised Ordering

- src/mediaproxies/mediamanager.js
- src/natives/rdk.js
Description
Modify updateSeekable of rdk native, to check for current time and throw network error in case it is outside the seekable window.
Tests
org.hbbtv_HTML5-DASH026
org.hbbtv_HTML5-DASH027
> Fix for org.hbbtv_HTML5-DASH026 and org.hbbtv_HTML5-DASH026

- android/orbpolyfill/src/main/java/org/orbtv/orbpolyfill/BridgeTypes.java
- src/objects/dashevent.js
DASHEvent id property is lowercase. Id appearing in the specification was a typo:
https://redmine.hbbtv.org/issues/13576
This should fix org.hbbtv_DVBI_EVENTS0060 and org.hbbtv_DVBI_EVENTS0130
> DASHEvent id property is lowercase. Id was a typo.

- rdk/ORB/library/src/core/requestHandlers/NetworkRequestHandler.cpp
- rdk/ORB/library/src/platform/ORBPlatform.h
- rdk/ORB/platform-mock/src/ORBPlatformMockImpl.cpp
- rdk/ORB/platform-mock/src/ORBPlatformMockImpl.h
- src/mediaproxies/mediamanager.js
Description
Addition of resolveNetworkError api to fix org.hbbtv_DASH-ERRORREP0006 and org.hbbtv_DASH-ERRORREP0007. This is an rdk specific change.
Tests:
org.hbbtv_DASH-ERRORREP0006
org.hbbtv_DASH-ERRORREP0007
> Add mediaManager resolveNetworkError api for errorreport tests

- android/mock204app/src/main/java/org/orbtv/mock204app/MockOrbSessionCallback.java
- In MockOrbSessionCallback, add a simple settings mode for query settings
- a switch for settings modes
Testing:
- HbbtvTestMaterials
- org.hbbtv_A11YSUBS_0010
- org.hbbtv_A11YSUBS_0020
- org.hbbtv_A11YSUBS_0030
> HTM-780 support three modes for subtitles

- src/mediaproxies/dashproxy.js
- src/mediaproxies/mediamanager.js
- src/mediaproxies/tracklists/texttracklist.js
- src/natives/rdk.js
Description
Addition of new rdk native events, used to track changes on different mpds regarding EventStream and changes to different Representations regarding InbandEventStream. The changes are rdk specific except some helper methods that will not affect the functionality.
Tests
org.hbbtv_DASH-EVENT0110
org.hbbtv_DASH-EVENT0120
org.hbbtv_DASH-EVENT0130
org.hbbtv_DASH-EVENT0140
> Implement rdk solution for dk-org.hbbtv_DASH-EVENT110+

- android/mock204app/src/main/java/org/orbtv/mock204app/MockOrbSessionCallback.java
Description:
- If DE is switched off, dialogueEnhancementGainPreference shall be also set to 0, like dialogueEnhancementGain.
Testing:
- All DE test of HbbTv204 test. 
You may need Set Setup > Manual > Interactive Test Steps to Yes in the Harness.
> HTM-807 dialogueEnhancementGainPreference shall be zero

- rdk/ORB/library/src/core/requestHandlers/ConfigurationRequestHandler.cpp
- rdk/ORB/library/src/platform/ORBPlatform.h
- rdk/ORB/platform-mock/src/ORBPlatformMockImpl.cpp
- rdk/ORB/platform-mock/src/ORBPlatformMockImpl.h
Description
Enable endpoint for Configuration.getCleanAudioEnabled API in RDK
Tests:
org.hbbtv_HTML50160
org.hbbtv_HTML50165
> Add implementation for Configuration.getCleanAudioEnabled api

- src/mediaproxies/tracklists/audiotracklist.js
Description
Fix for cases when the prefered language returned by platform, is a comma separated list
Tests
org.hbbtv_HTML50160
org.hbbtv_HTML50165
> Add handling for pref language

- src/mediaproxies/dashproxy.js
Ignore errors when xlink:href couldn't be fetched.
Xlink attributes are simply removed by dash.js, and it will use the adaptation set defined locally in MPD.
> Pass org.hbbtv_DASH-XLINK0013

- src/objects/avcontrol.js
According to HbbTV Annex A.2.12.3 Modifications to clause 8.4.6, "Where
an AudioTrack corresponds to an MPEG DASH adaptation set or
Preselection, the value of the AudioTrack.language attribute shall be
the value of the lang attribute in the MPD". And that is an ISO 639-1
two-character code, the conversion is not necessary for DASH.
> Fix OpenRedButtonProject/orb/pull/274 regression

- android/mock204app/src/main/java/org/orbtv/mock204app/MockAit.java
- android/mock204app/src/main/java/org/orbtv/mock204app/TestSuiteScenario.java
- android/orblibrary/src/main/cpp/application_manager_native.cpp
- android/orblibrary/src/main/java/org/orbtv/orblibrary/ApplicationManager.java
- android/orblibrary/src/main/java/org/orbtv/orblibrary/BrowserView.java
- android/orblibrary/src/main/java/org/orbtv/orblibrary/OrbSession.java
- components/application_manager/ait.cpp
- components/application_manager/ait.h
- components/application_manager/app.cpp
- components/application_manager/app.h
- components/application_manager/application_manager.cpp
- components/application_manager/application_manager.h
- components/application_manager/xml_parser.cpp
- tests/debug/json_rpc/scenario.json
- tests/launchers/mitxperts/scenario.json
COD-64 add graphicsConstraints in ait and xml ait
- parse graphicsConstraints in ait and xml ait
- update app
- update scenario file
COD-65 update graphics info in application manager and browserView
- send graphics info to the callback of application manager
- graphics info is only active when OrbHbbTVVersion >= 204
- scale the browserView based on the highest supported resolution
Testing:
- manual checking with mit-xpert
https://github.com/OceanBlueSoftware/mitxp-testsuite/pull/3
when OrbHbbTVVersion >= 204, scaling browserView based on the supported resolution;
in other cases, scaling to default app size (1280x720)
> COD-36 support for high resolution graphics

- src/mediaproxies/tracklists/texttrackcuelist.js
Description
The text cues need to be in charCode form for test org.hbbtv_DASH-131-EVENTS0120 to pass. Ensure that the text cue array holds those charCodes in orb_addCue
Tests
org.hbbtv_DASH-131-EVENTS0120
> Modify orb_addCue to ensure cue list is a charCode array

- src/mediaproxies/dashproxy.js
The test will eventually try to download a 1080p segment of ~2600000 bytes when the bandwidth is restricted to 1100000 bps. This would take 2600000 * 8 / 1100000 = 18 seconds, when Dashjs default timeout is 10 seconds (set in /src/core/Settings.js Line 865).
Recent versions of Dashjs use a default value of 20 seconds for fragmentRequestTimeout as well:
https://github.com/Dash-Industry-Forum/dash.js/blob/ca4c7aa0227d001bb31801faa61a2d57c4e14da4/src/core/Settings.js#L1162
> Pass org.hbbtv_DASH-SE0031

- src/mediaproxies/dashproxy.js
- src/mediaproxies/mediamanager.js
HBBTV 9.4.2
The origin of the media timeline used by HTML5 media elements (i.e. the &lt;audio&gt; and &lt;video&gt; elements) shall be the start time of the first Period that was defined in the MPD when the MPD was first loaded. The origin of the media timeline shall not change unless the HTML5 media element source is changed or the load() method is called. [...] For a dynamic MPD, getStartDate() shall return a Date oject representing the value of MPD@availabilityStartTime plus the PeriodStart time (see clause 5.3.2.1 of MPEG DASH ISO/IEC 23009-1 [29]) of the first regular Period when the MPD was first loaded.
Thus:
- startDate is only calculated once.
- startDate is forgotten on load() calls.
In addition to that, the loadeddata event is not triggered for this MPD (first period has a …
> Pass org.hbbtv_HTML5-DASH003

- rdk/ORB/library/src/core/ORBEngine.h
- rdk/ORB/library/src/core/requestHandlers/BroadcastRequestHandler.cpp
- rdk/ORB/library/src/core/utilities/MetadataSearchTask.cpp
- rdk/ORB/library/src/core/utilities/MetadataSearchTask.h
Description
Test org.hbbtv_0000F000 fails consistently and the reason of failure is related to the way we handle the MetadataSearchTask removal. Apply the changes that Sky proposed to fix the issue
Tests
org.hbbtv_0000F000
> Thread cancel and MetadataSearchTask remove

- src/objects/avcontrol.js
In dynamic DASH MPDs, the seek operation is relative to the startDate (MPD@availabilityStartTime plus the PeriodStart time of the first regular Period when the MPD was first loaded).
priv.startDate only gets a non null value when the MPD is dynamic.
> Fix org.hbbtv_DASH-TIMELINE0140

- android/orblibrary/src/main/java/org/orbtv/orblibrary/WebResourceClient.java
.cehtml files coming from the carousel have to have application/xhtml+xml mime type, instead of text/html. Otherwise some self closed elements like <object /> would be hanlded as the beginning of the <object> tag, and mess how the page is interpreted
> Fix org.hbbtv_E1210060 and org.hbbtv_E1210070

- src/mediaproxies/nativeproxy.js
- src/mediaproxies/tracklists/texttracklist.js
The original video element gets the subtitle track mode set to 'showing' before the iframe player gets initialised. A call setting mode to 'showing' is needed to get the iframe player to handle the required change.
> Fix org.hbbtv_SUB0120

- src/objects/avcontrol.js
During dash.js initialisation a seek operation is performed before starting to play the stream. avcontrol.js will mistakenly transition to PLAYING state. avcontrol.js just needs to ignore this operation while it is in the initialisation phase (before play is called).
> Fix org.hbbtv_DASH-TIMELINE0070 and org.hbbtv_DASH-TIMELINE0150

- src/mediaproxies/tracklists/texttrack.js
- src/mediaproxies/tracklists/texttracklist.js
Take into account the mode of the original media element's text track with the media element extension.
> Fix org.hbbtv_RELIABILITY05.

- src/polyfill/keyevent.js
The following tests are failing because KeyboardEvent does not contain a valid code attribute as specified in HbbTV 10.2.2.1 Key events:
org.hbbtv_00000580
org.hbbtv_00000590
org.hbbtv_00000600
org.hbbtv_00000610
org.hbbtv_00000620
org.hbbtv_00000630
org.hbbtv_00000640
org.hbbtv_00000650
org.hbbtv_00000660
org.hbbtv_00000670
org.hbbtv_00000680
org.hbbtv_00000690
org.hbbtv_00000700
org.hbbtv_00000710
org.hbbtv_00000720
org.hbbtv_00000730
org.hbbtv_00000740
org.hbbtv_00000750
org.hbbtv_00000760
org.hbbtv_00000770
org.hbbtv_00000780
org.hbbtv_00000790
org.hbbtv_00000800
org.hbbtv_00000820
> HTM-775 add KeyboardEvent code attribute as specified in HbbTV 10.2.2.1 Key events

- android/mock204app/src/main/java/org/orbtv/mock204app/MockOrbSessionCallback.java
Description:
- Change accessibility keycode from 1-8 to keycode f1-f8. As well as Rich settings keycode 0 to f10.
- Use adb shell command: -- "key_f1": "adb shell input keyevent 131", -- "key_f2": "adb shell input keyevent 132", -- "key_f3": "adb shell input keyevent 133", -- "key_f4": "adb shell input keyevent 134", -- "key_f5": "adb shell input keyevent 135", -- "key_f6": "adb shell input keyevent 136", -- "key_f7": "adb shell input keyevent 137", -- "key_f8": "adb shell input keyevent 138", -- "key_f10": "adb shell input keyevent 140",
Testing:
- Accessibility tests
- HTM-797 VK_NUMERIC keyEvents for KEYREQCONXXX tests
> HTM-797 Change keycode

- android/mockdialservice/.gitignore
- android/orblibrary/CMakeLists.txt
- android/orblibrary/src/main/cpp/application_manager_native.cpp
- components/application_manager/opapp.cpp
- components/application_manager/opapp.h
This fixes a few build errors when trying to build mock203app. But it doesn't fix all of them!!
1) opapp.cpp needed to be added to CMakeLists.txt for orblibrary
2) Utils::Timeout initialisation used deleted constructor. Now initialisation in OpApp constructor list.
Also adds .gitignore for mockdialservice.
> FREE-85 fix build errors

- BUILD.gn
- orblibrary/BUILD.gn
- orblibrary/include/HtmlBuilder.h
- orblibrary/polyfill/HtmlBuilder.cpp
- orblibrary/polyfill/polyfill_unittest.cpp
- scripts/concat.py
- scripts/embed_file.py
Constructs the Hbbtv.js from fragments using Chromium BUILD.gn. A python script concatenates the sources before building into a static library using a second script - embed_file.py.
There's probably a bit more here than needed as some of the extra concatenations are done. These will be used in future, see backlog ticket [FREE-88](https://oceanbluesoftware.atlassian.net/browse/FREE-88).
I've added a small unit test to check if the build works and my library contains a few important fragments.
[FREE-88]: https://oceanbluesoftware.atlassian.net/browse/FREE-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FREE-62 Create polyfill js

- Jenkinsfile
Add a Jenkins pipeline that updates the DEPS file of the Chromium repo with the latest ORB repo commit (in the Chromium project this process is known as "rolling").
NB: If both Chromium and ORB are branched and an auto roller is setup for the branch, the parameter DEPS_REPO_BRANCH within the Jenkinsfile of the ORB branch will need to be updated with the correct Chromium repo branch to change.
> FREE-128 jenkins: create orb auto roller

- BUILD.gn
- external/libwebsockets/v4.3/BUILD.gn
- scripts/apply_patch.py
1. Apply libwebsockets patch in out temporary folder with GN to avoid updating code in third_party folder with Gclient hooks
2. Turn on orb_network_services dependency.
> FREE-131 Apply libwebsockets patch in out folder with GN
